
version: "3.9"
services:
  api:
    build: ./platform
    ports: ["3000:3000"]
    env_file: [.env]
    depends_on: [mongo, redis]

  mongo:
    image: mongo:7
    ports: ["27017:27017"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
